### ISSUE TITLE
Wrong import endpoint on first-example.md

### ISSUE THREAD

**Issue by kevin92dev** [apisearch-io/docs#5]
The right endpoint for import feeds is 
`http://localhost:8100/v1/marvel/indices/comics/import/by-feed?feed=file:///marvel.as`
instead of
`http://localhost:8100/v1/marvel/indices/comics/import?feed=file:///marvel.as`

**Comment by mmoreram** [comment]
@kevin92dev thanks! Could you tell me where you found this issue? I can't find any reference right now in these docs!

**Comment by kevin92dev** [comment]
@mmoreram in first-example.md file, before the text “Great! If your reading this, you can be proud you already have a data set of more than 11K...”. The curl request has a wrong example URL.

**Comment by mmoreram** [comment]
@kevin92dev Fixed

https://github.com/apisearch-io/docs/commit/f9da6814d5bbea3f6331c0bc4ea2bb48c99a1a67

Thanks so much :D
